const constants = {
	SET_INITIAL_STATE: "SET_INITIAL_STATE",
	SET_NUM_INTERVALS: "SET_NUM_INTERVALS",
	SET_REST_TIME: "SET_REST_TIME",
	SET_INTERVAL_TIME: "SET_INTERVAL_TIME",
	SET_REST_INCREMENT: "SET_REST_INCREMENT",
	SET_TIMER_NAME: "SET_TIMER_NAME",
	SAVE_TIMER: "SAVE_TIMER",
	CLEAR_TIMER_FORM: "CLEAR_TIMER_FORM",
	EDIT_TIMER: "EDIT_TIMER",
	DELETE_TIMER: "DELETE_TIMER",
	CHOOSE_TIMER: "CHOOSE_TIMER",
	START_TIMER: "START_TIMER",
	SET_TOTAL_TIME: "SET_TOTAL_TIME",
	SET_LOGIN_UID: "SET_LOGIN_UID",
	LOGOUT: "LOGOUT"
}

export default constants;
