const constants = {
	SET_NUM_INTERVALS: "SET_NUM_INTERVALS",
	SET_REST_TIME: "SET_REST_TIME",
	SET_INTERVAL_TIME: "SET_INTERVAL_TIME",
	SET_REST_INCREMENT: "SET_REST_INCREMENT",
	SET_TIMER_NAME: "SET_TIMER_NAME",
	SAVE_TIMER: "SAVE_TIMER",
	CLEAR_FORM: "CLEAR_FORM",
	EDIT_TIMER: "EDIT_TIMER"
}

export default constants;
